steps:
  - name: node:14
    entrypoint: npm
    args: ['install']
  - name: 'ubuntu'
    args: [ 'bash', './myscript.sh' ]
    env:
      - 'apiKey=$API_KEY'
      - 'authDomain=$AUTH_DOMAIN'
      - 'databaseURL=$DATABASE_URL'
      - 'projectId=$PROJECT_ID'
      - 'storageBucket=$STORAGE_BUCKET'
      - 'messagingSenderId=$MESSAGING_SENDER_ID'
      - 'appId=$APP_ID'
      - 'measurementId=$MEASUREMENT_ID'
  - name: node:14
    entrypoint: npm
    args: ['run', 'build' ]
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: [ -c, gcloud app deploy ./dist/app.yaml ]
timeout: "1600s"
